using System.Collections;
using UnityEngine;
using Spine;
using Spine.Unity;
using NUnit.Framework;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;


public class PlayerMove : MonoBehaviour
{
    //ì œë°œì¢€
    //ì§„ì§œì œë°œ
    [SerializeField] private SkeletonAnimation spinePlayer;

    public bool isPortal = false; //í¬íƒˆ
    public string currentGroundTag = "";
    public GameObject slashPrefab; 
    public Transform firePoint; // ë°œì‚¬ ìœ„ì¹˜

    private bool attackSoundPlayed = false; //ì‚¬ìš´ë“œ ì†Œë¦¬ í•œë²ˆë§Œ ë“¤ë¦¬ê²Œ

    public bool isDropping = false;


    public static PlayerMove instance;

    private Collider2D _playerCollid;

   
    public Collider2D PlayerCollider 
    {
        get 
        {
            if (_playerCollid == null)
            {
                _playerCollid = GetComponent<Collider2D>();
            }
            return _playerCollid;
        }
    }

    

    public float damageDuration = 0.5f; //ë°ë¯¸ì§€ íŒì • ìœ ì§€ì‹œê°„
    public GameObject damageObject;
    private bool isAttacking = false;
    private bool isCoolingDown = false; 
    private bool skinCooling = false; //qìŠ¤í‚¬
    public float skinCooldownTime = 8f;
    private bool skillCooling = false;
    public float skillCooldownTime = 10f; //sìŠ¤í‚¬

    public float attackCooldown = 1.5f; //ê³µê²© ì¿¨íƒ€ì„



    [Header("ì´ë™ ë° ì í”„")]
    public float speed = 5f;
    public float jumpPower = 11f;
    private int maxJumpCount = 2;
    public int currentJumpCount = 0;
    public bool isGround = true;

    [Header("ëŒ€ì‹œ")]
    public float dashPower = 15f;
    public float dashTime = 0.2f;
    public float dashingCooldown = 1f;
    bool canDash = true;
    bool dashing = false;

    [Header("ê°€ë©´")]
    public GameObject ImNormal;
    public GameObject ImRed;
    public GameObject ImBlue;
    public GameObject ImBlack;

    public GameObject QCool;
    public GameObject SCool;

    bool isNormal = true;
    bool isRed = false;
    bool isBlue = false;
    bool isBlack = false;

    bool isAttack; 
    public bool isDead = false;

    [Header("ìŠ¤í‚¬")]
    public SkeletonAnimation skeletonAnimation;

    [Header("ì»´í¬ë„ŒíŠ¸ ë° ìƒíƒœ")]
    public Rigidbody2D rigid;
    public Collider2D groundCheckCollider;
    public LayerMask whatIsGround; // ì§€ë©´ ë ˆì´ì–´ ì„¤ì •
    private float moveInput = 0f;
    private bool isFacingRight = true;

    void Awake()
    {
        
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject); // ì”¬ ì´ë™ì—ë„ ìœ ì§€
            SceneManager.sceneLoaded += OnSceneLoaded;
            _playerCollid = GetComponent<Collider2D>(); 
        }
        else
        {
            Destroy(gameObject);
        }
    }

    void OnDestroy()
{
    SceneManager.sceneLoaded -= OnSceneLoaded;
}

private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
{
    GameObject spawnPointObject = GameObject.FindGameObjectWithTag("SpawnPoint");

    if (spawnPointObject != null)
        transform.position = spawnPointObject.transform.position;

    spinePlayer = GetComponentInChildren<SkeletonAnimation>();
    skeletonAnimation = GetComponentInChildren<SkeletonAnimation>();

    // ğŸ”¥ ì´ë™/í–‰ë™ ê´€ë ¨ ìƒíƒœ ì´ˆê¸°í™”
    isPortal = false;
    isAttack = false;
    dashing = false;
    canDash = true;
    moveInput = 0;
    isDead = false;
}


    void Start()
    {

        
        SCool.SetActive(false);
        QCool.SetActive(false);

        rigid = GetComponent<Rigidbody2D>();
        if (spinePlayer != null)
        {
            SetAnimationState("idle");
        }

        skeletonAnimation = GetComponent<SkeletonAnimation>();
        if (skeletonAnimation != null && skeletonAnimation.skeleton != null)
        {
            skeletonAnimation.skeleton.SetSkin("normal");
            skeletonAnimation.skeleton.SetupPoseSlots();
        }

        if (ImNormal != null) ImNormal.SetActive(true);
    }

    void Update()
    {
        if (isPortal)
{
    moveInput = 0f;
    SetAnimationState("idle");
    return;
}
        if (isDead) return;
        
        // ì´ë™ ì…ë ¥ (ê³µê²©,ëŒ€ì‹œ ì¤‘ì—ëŠ” ì…ë ¥ ë¬´ì‹œ)
        moveInput = 0f;
        if ( !dashing)
        {
            if (Input.GetKey(KeyCode.RightArrow))
            {
                moveInput = 1f;
            }
            else if (Input.GetKey(KeyCode.LeftArrow))
            {
                moveInput = -1f;
            }
        }
        
        // ì§€ìƒ ì• ë‹ˆë©”ì´ì…˜ (idle/walk)
        if (isGround && !dashing && !isAttack)
        {
            if (moveInput != 0f)
            {
                SetAnimationState("walk");
            }
            else
            {
                SetAnimationState("idle");
            }
        }

       if (Input.GetKeyDown(KeyCode.A) && !dashing && !isAttack && isGround)
{
    isAttack = true;
    attackSoundPlayed = false; // ìƒˆ ê³µê²© ì‹œì‘


    var track = spinePlayer.AnimationState.SetAnimation(0, "attack", false);

    // ì‚¬ìš´ë“œ í•œ ë²ˆë§Œ ì¬ìƒ
    if (!attackSoundPlayed)
    {
        
        attackSoundPlayed = true;
    }

    StartCoroutine(NormalAttackRoutine());

    track.Complete += (t) =>
    {
        isAttack = false;
        OnActionComplete();
    };
}

if (Input.GetKeyDown(KeyCode.S) && !dashing && !isAttack && isGround && !skillCooling)
{
    SCool.SetActive(true);
    StartCoroutine(SkillCooldown());
    
    isAttack = true;
    Spine.TrackEntry track = null;
    

    if (isNormal) track = spinePlayer.AnimationState.SetAnimation(0, "skill_normal", false);
    else if (isRed) track = spinePlayer.AnimationState.SetAnimation(0, "skill_red", false);
    else if (isBlue) track = spinePlayer.AnimationState.SetAnimation(0, "skill_blue", false);
    else track = spinePlayer.AnimationState.SetAnimation(0, "skill_black", false);

    StartCoroutine(SkillAttackRoutine());

    track.Complete += (t) =>
    {
        isAttack = false;
        OnActionComplete();
    };
}

        // ì í”„
        if (Input.GetKeyDown(KeyCode.Space) && currentJumpCount < maxJumpCount && !isAttack && !dashing)
        {

            Jump();
        }

        // ëŒ€ì‰¬
        if (Input.GetKeyDown(KeyCode.LeftShift) && canDash && !isAttack)
        {
            AudioManager.instance.PlaySfx(AudioManager.Sfx.Jump);
            StartCoroutine(Dash());
        }

        // ìŠ¤í‚¨ ì „í™˜ Qí‚¤
        if (Input.GetKeyDown(KeyCode.Q) && !dashing && !isAttack && !skinCooling)
        {
            QCool.SetActive(true);
            StartCoroutine(SkinCooldown());
            ChangeSkinCycle();
            

            
        }

        if (!dashing)
        {
            Flip();
        }

        
    } // Update ì¢…ë£Œ
    IEnumerator SkillCooldown()
    {
        skillCooling = true;
        yield return new WaitForSeconds(skillCooldownTime);
        skillCooling = false;
        SCool.SetActive(false);
    }

    void FixedUpdate()
    {
        if (!dashing)
        {
            rigid.linearVelocity = new Vector2(moveInput * speed, rigid.linearVelocity.y);
            GroundCheck();
        }
    }



    void Jump()
    {
        AudioManager.instance.PlaySfx(AudioManager.Sfx.Jump);
        SetAnimationState("jump", false);
        rigid.linearVelocity = new Vector2(rigid.linearVelocity.x, jumpPower);
        currentJumpCount++;
        isGround = false;
    }

    void Flip()
    {
        if ((isFacingRight && moveInput < 0f) || (!isFacingRight && moveInput > 0f))
        {
            isFacingRight = !isFacingRight;
            Vector3 localScale = transform.localScale;
            localScale.x *= -1f;
            transform.localScale = localScale;
        }
    }
        IEnumerator SkinCooldown() //qìŠ¤í‚¬ì¿¨íƒ€ì„
    {
      skinCooling = true;
      AudioManager.instance.PlaySfx(AudioManager.Sfx.Mask);
        yield return new WaitForSeconds(skinCooldownTime);
      skinCooling = false;
      QCool.SetActive(false);
    }

    void ChangeSkinCycle() //ê°€ë©´ë³€í™˜
{
    if (isNormal)
    {
        isRed = true; isNormal = false;
        ImRed?.SetActive(true);
        ImNormal?.SetActive(false);
        skeletonAnimation.skeleton.SetSkin("red");
    }
    else if (isRed)
    {
        isBlue = true; isRed = false;
        ImBlue?.SetActive(true);
        ImRed?.SetActive(false);
        skeletonAnimation.skeleton.SetSkin("blue");
    }
    else if (isBlue)
    {
        isBlack = true; isBlue = false;
        ImBlack?.SetActive(true);
        ImBlue?.SetActive(false);
        skeletonAnimation.skeleton.SetSkin("black");
    }
    else
    {
        isNormal = true; isBlack = false;
        ImNormal?.SetActive(true);
        ImBlack?.SetActive(false);
        skeletonAnimation.skeleton.SetSkin("normal");
    }

    skeletonAnimation.skeleton.SetupPoseSlots();
} 

    // ì°©ì§€ ì´ë²¤íŠ¸ í•¸ë“¤ëŸ¬
    void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.collider.CompareTag("DownGround"))
    {
        currentGroundTag = "DownGround";
    }
    else if (collision.collider.CompareTag("floor"))
    {
        currentGroundTag = "floor";
    }
    else
    {
        currentGroundTag = collision.collider.tag;
    }

        if (collision.gameObject.CompareTag("floor") || collision.gameObject.CompareTag("DownGround") )
        {
            isAttack = true;
            currentJumpCount = 0;
            isGround = true;
        
            var track = spinePlayer.AnimationState.SetAnimation(0, "landing", false);
            track.Complete += OnLandingComplete; // ë©”ì„œë“œ ì—°ê²°
            isAttack = false;
        }

        
    }

    void OnCollisionExit2D(Collision2D collision)
{
    if (!string.IsNullOrEmpty(currentGroundTag))
    {
        if (collision.collider.CompareTag(currentGroundTag))
        currentGroundTag = "";
        }
}

    

    private void OnLandingComplete(TrackEntry trackEntry)
    {
       
        if (!dashing && !isAttack) 
        {
            if (moveInput != 0f) SetAnimationState("walk");
            else SetAnimationState("idle");
        }
    }
    
    // ê³µê²©/ìŠ¤í‚¬/ëŒ€ì‹œ ì™„ë£Œ í›„
    private void OnActionComplete()
    {
        if (isGround && !dashing)
        {
            if (moveInput != 0) SetAnimationState("walk");
            else SetAnimationState("idle");
        }
        // ê³µì¤‘ì´ë¼ë©´ fall ì• ë‹ˆë©”ì´ì…˜
        else if (!isGround && !dashing)
        {
            if (rigid.linearVelocity.y < -0.1f)
            {
                SetAnimationState("landing", true);
            }
            
        }
    }


    IEnumerator Dash()
    {
        
        canDash = false;
        dashing = true;

        float originalGravity = rigid.gravityScale;
        rigid.gravityScale = 0f;

        float dashDirection = isFacingRight ? 1f : -1f;
        rigid.linearVelocity = new Vector2(dashDirection * dashPower, 0f);

        yield return new WaitForSeconds(dashTime);

        rigid.gravityScale = originalGravity;

        OnActionComplete(); 

        dashing = false;

        yield return new WaitForSeconds(dashingCooldown);
        canDash = true;
    }

    void SetAnimationState(string animName, bool loop = true)
    {
        if (isDead && animName != "dead") return;
        if (spinePlayer == null) return;

        string currentAnim = spinePlayer.AnimationState.GetCurrent(0)?.Animation?.Name;
        if (currentAnim == animName) return;

        spinePlayer.AnimationState.SetAnimation(0, animName, loop);
    }

    void GroundCheck()
    {
        if (groundCheckCollider == null) return; 

        BoxCollider2D boxCollider = groundCheckCollider as BoxCollider2D;
        if (boxCollider == null)
        {
            isGround = false; 
            return;
        }

        Vector2 origin = boxCollider.bounds.center;
        Vector2 size = boxCollider.bounds.size;
        float checkDistance = 0.2f;

        RaycastHit2D GroundBoxHit = Physics2D.BoxCast(origin, size, 0f, Vector2.down, checkDistance, whatIsGround);

        if (GroundBoxHit)
        {
            if (GroundBoxHit.collider.CompareTag("MovingPlatform") || GroundBoxHit.collider.CompareTag("OneWayPlatform"))
            {
                
                isGround = GroundBoxHit.collider.bounds.max.y <= boxCollider.bounds.min.y + 0.1f;
            }
            else
            {
                isGround = true; 
            }
        }
        else
        {
            isGround = false;
        }
    }

    public void PlatformDrop() //í•˜í–¥ì í”„
    {
        SetAnimationState("landing", true);
        isGround = false;

        if (rigid != null)
    {
        rigid.linearVelocity = new Vector2(rigid.linearVelocity.x, -5f); // ì†ë„ëŠ” ì¡°ì ˆ ê°€ëŠ¥
    }
    }

    public void KillAni()
    {
        isDead = true;
        SetAnimationState("dead", false);
    }
    
    public Â void SetIsAttack(bool state) 
    {
        isAttack = state;

        // ê³µê²© ìƒíƒœê°€ í•´ì œë  ë•Œ
        if (!isAttack)
        {
            OnActionComplete(); // ì• ë‹ˆë©”ì´ì…˜ ìƒíƒœ ë³µê·€
        }
    }

    IEnumerator NormalAttackRoutine()
{
    if (damageObject == null) yield break;

    

    float baseDamage = 10f;
    float finalDamage = baseDamage;

    

    // íƒ€ê²© íƒ€ì´ë° (ì• ë‹ˆë©”ì´ì…˜ 0.2ì´ˆ í›„)
    yield return new WaitForSeconds(0.2f);

    damageObject.GetComponent<PlayerDamage>().SetDamage(finalDamage);
    damageObject.SetActive(true);

    yield return new WaitForSeconds(damageDuration);
    damageObject.SetActive(false);

}

IEnumerator SkillAttackRoutine() //ìŠ¤í‚¬
{
    
    if (damageObject == null) yield break;

    float baseDamage = 20f; //ê¸°ë³¸ ìŠ¤í‚¬ ë°ë¯¸ì§€ (ë¸”ë£¨ë‘ ë…¸ë©€ ê¸°ë³¸ 20 ë°ë¯¸ì§€)
    float finalDamage = baseDamage;

    if(isNormal)
        {
            AudioManager.instance.PlaySfx(AudioManager.Sfx.Normal);
            StartCoroutine(Dash());
            damageObject.SetActive(true);
            yield return new WaitForSeconds(damageDuration);
            damageObject.SetActive(false);
        }

        if (isRed)
    {
        AudioManager.instance.PlaySfx(AudioManager.Sfx.Red);
    }

    if (isBlue)
    {
        AudioManager.instance.PlaySfx(AudioManager.Sfx.Blue);
        FireSlash();
    }

    if (isBlack)
    {
        AudioManager.instance.PlaySfx(AudioManager.Sfx.Black);
    }


    if (isRed) finalDamage += 10f; //í™”ì—¼ +10 ë°ë¯¸ì§€
    if (isBlack) finalDamage += 20f; //ë¸”ë™ +20 ë°ë¯¸ì§€ 
    
      
    yield return new WaitForSeconds(0.15f); 

    if(!isNormal)
    {
    damageObject.GetComponent<PlayerDamage>().SetDamage(finalDamage);
    damageObject.SetActive(true);
    if (isBlack)
    { Â 
        PlayerDamage pd = damageObject.GetComponent<PlayerDamage>();
        if (pd != null)
            pd.isBlackSkill = true;
    }

    yield return new WaitForSeconds(damageDuration);
    damageObject.SetActive(false);
    }
}



void FireSlash()
{
    if (slashPrefab == null || firePoint == null) return;

    Vector2 dir = isFacingRight ? Vector2.right : Vector2.left;
    GameObject slash = Instantiate(slashPrefab, firePoint.position, Quaternion.identity);
    slash.SetActive(true);

    SpriteRenderer sr = slash.GetComponent<SpriteRenderer>();
    sr.flipX = isFacingRight;

    
    
    SlashProjectile proj = slash.GetComponent<SlashProjectile>();
    if (proj != null)
    {
        proj.Init(dir, 20f); // ë°ë¯¸ì§€ ì„¤ì • ê°€ëŠ¥
    }
}





    

    
    IEnumerator AttackDelay()
    {
        isCoolingDown = true; 
        yield return new WaitForSeconds(attackCooldown); 
        isCoolingDown = false; 
    }

public void SetDamageObjectActive(bool state, float damage)
{
    if (damageObject == null) return;

    PlayerDamage playerDamage = damageObject.GetComponent<PlayerDamage>();
    if (playerDamage != null)
    {
        playerDamage.SetDamage(damage);
    }
    
    damageObject.SetActive(state);
}




}